"""add request_group_id to messages

Revision ID: 01d224b4e0f2
Revises: df457569bcf1
Create Date: 2026-09-19 23:20:02.121300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d224b4e0f2'
down_revision: Union[str, Sequence[str], None] = 'df457569bcf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('request_group_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'request_group_id')
    # ### end Alembic commands ###
