"""add message_id to usage_events

Revision ID: 4bcd098e7789
Revises: 9e0a4389a14d
Create Date: 2026-09-20 15:22:54.917596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bcd098e7789'
down_revision: Union[str, Sequence[str], None] = '9e0a4389a14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: dropped the autogenerated ix_chunks_content_fts drop/recreate -- that
    # GIN functional index isn't expressed in the ORM model, so autogenerate always
    # misdetects it as removed. Unrelated to this migration; left untouched.
    op.add_column('usage_events', sa.Column('message_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'usage_events_message_id_fkey', 'usage_events', 'messages', ['message_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usage_events_message_id_fkey', 'usage_events', type_='foreignkey')
    op.drop_column('usage_events', 'message_id')
    # ### end Alembic commands ###
