"""add used_system_key to usage_events

Revision ID: 6c7d99ebaf68
Revises: 09f44478e86c
Create Date: 2026-09-20 13:02:59.617515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7d99ebaf68'
down_revision: Union[str, Sequence[str], None] = '09f44478e86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: dropped the autogenerated ix_chunks_content_fts drop/recreate -- that
    # GIN functional index isn't expressed in the ORM model, so autogenerate always
    # misdetects it as removed. Unrelated to this migration; left untouched.
    op.add_column('usage_events', sa.Column('used_system_key', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('usage_events', 'used_system_key', server_default=None)
    op.alter_column('usage_events', 'provider_key_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_events', 'provider_key_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('usage_events', 'used_system_key')
    # ### end Alembic commands ###
