"""create agents table

Revision ID: 7cc6996053ca
Revises: 6c7d99ebaf68
Create Date: 2026-09-20 13:09:38.468441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc6996053ca'
down_revision: Union[str, Sequence[str], None] = '6c7d99ebaf68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('primary_goal', sa.Text(), nullable=False),
    sa.Column('output_format', sa.Enum('STRUCTURED_MARKDOWN', 'STRICT_JSON', 'EXECUTIVE_BRIEF', 'CUSTOM', name='output_format_enum'), nullable=False),
    sa.Column('output_instructions', sa.Text(), nullable=True),
    sa.Column('json_schema', sa.JSON(), nullable=True),
    sa.Column('guardrail_patterns', sa.JSON(), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('is_deployed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agents')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS output_format_enum')
