"""add flagged to messages

Revision ID: 9e0a4389a14d
Revises: 7cc6996053ca
Create Date: 2026-09-20 13:16:02.379882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0a4389a14d'
down_revision: Union[str, Sequence[str], None] = '7cc6996053ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: dropped the autogenerated ix_chunks_content_fts drop/recreate -- that
    # GIN functional index isn't expressed in the ORM model, so autogenerate always
    # misdetects it as removed. Unrelated to this migration; left untouched.
    op.add_column('messages', sa.Column('flagged', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('messages', 'flagged', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'flagged')
    # ### end Alembic commands ###
