"""create mcp_servers table, add mcp_server_ids to agents

Revision ID: 9f4f507fca3a
Revises: 4bcd098e7789
Create Date: 2026-09-20 15:40:01.601481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4f507fca3a'
down_revision: Union[str, Sequence[str], None] = '4bcd098e7789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('connection_url', sa.String(), nullable=False),
    sa.Column('encrypted_token', sa.LargeBinary(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'agents',
        sa.Column('mcp_server_ids', sa.JSON(), nullable=False, server_default='[]'),
    )
    # ponytail: known autogenerate false-positive on the FTS index, not a real drift -- skip it
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'mcp_server_ids')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
